VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IXMLReader"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

''' VBAによるインターフェイス定義
''' 実装は空にしておくこと
''' 参考: http://www.cpearson.com/excel/Implements.aspx

Public Function GetContent(URL As String) As String
' -------------------------------------------
' URLを指定してXMLを取得する.
'
' Parameter:
'   [URL] IN 取得するXMLのURL
'
' Return value:
'   取得されたXML
' -------------------------------------------
    ' declaration only. no code allowed.
End Function

